/*
 * generated by Xtext 2.12.0
 */
package de.tgremple.siteanalyser.configuration.idea


/**
 * Use this class to register components to be used within IntelliJ IDEA.
 */
class ConfigurationLanguageIdeaModule extends AbstractConfigurationLanguageIdeaModule {
}
