/*
 * generated by Xtext 2.12.0
 */
package de.tgremple.siteanalyser.configuration.idea

import org.eclipse.xtext.ISetup
import org.eclipse.xtext.idea.extensions.EcoreGlobalRegistries

class ConfigurationLanguageIdeaSetup implements ISetup {

	override createInjectorAndDoEMFRegistration() {
		EcoreGlobalRegistries.ensureInitialized
		new ConfigurationLanguageStandaloneSetupIdea().createInjector
	}

}
