/*
 * generated by Xtext 2.12.0
 */
package de.tgremple.siteanalyser.configuration.idea.lang.psi.impl;

import com.intellij.openapi.fileTypes.FileType;
import com.intellij.psi.FileViewProvider;
import de.tgremple.siteanalyser.configuration.idea.lang.ConfigurationLanguageFileType;
import de.tgremple.siteanalyser.configuration.idea.lang.ConfigurationLanguageLanguage;
import org.eclipse.xtext.psi.impl.BaseXtextFile;

public final class ConfigurationLanguageFileImpl extends BaseXtextFile {

	public ConfigurationLanguageFileImpl(FileViewProvider viewProvider) {
		super(viewProvider, ConfigurationLanguageLanguage.INSTANCE);
	}

	@Override
	public FileType getFileType() {
		return ConfigurationLanguageFileType.INSTANCE;
	}
}
