/*
 * generated by Xtext 2.12.0
 */
package de.tgremple.siteanalyser.configuration.idea.facet;

import com.intellij.facet.Facet;
import com.intellij.facet.FacetTypeId;
import de.tgremple.siteanalyser.configuration.idea.lang.ConfigurationLanguageLanguage;
import org.eclipse.xtext.idea.facet.AbstractFacetType;

public class ConfigurationLanguageFacetType extends AbstractFacetType<ConfigurationLanguageFacetConfiguration> {

	public static final FacetTypeId<Facet<ConfigurationLanguageFacetConfiguration>> TYPEID = new FacetTypeId<Facet<ConfigurationLanguageFacetConfiguration>>("de.tgremple.siteanalyser.configuration.ConfigurationLanguage");

	public ConfigurationLanguageFacetType() {
		super(TYPEID, "de.tgremple.siteanalyser.configuration.ConfigurationLanguage", "ConfigurationLanguage");
		ConfigurationLanguageLanguage.INSTANCE.injectMembers(this);
	}
}
