/**
 * generated by Xtext 2.12.0
 */
package de.tgremple.siteanalyser.configuration.idea.facet;

/* @State(, ) */@SuppressWarnings("all")
public class ConfigurationLanguageFacetConfiguration /* implements AbstractFacetConfiguration, PersistentStateComponent<GeneratorConfigurationState>  */{
}
