/**
 * generated by Xtext 2.12.0
 */
package de.tgremple.siteanalyser.configuration.configurationLanguage;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see de.tgremple.siteanalyser.configuration.configurationLanguage.ConfigurationLanguageFactory
 * @model kind="package"
 * @generated
 */
public interface ConfigurationLanguagePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "configurationLanguage";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.tgremple.de/siteanalyser/configuration/ConfigurationLanguage";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "configurationLanguage";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ConfigurationLanguagePackage eINSTANCE = de.tgremple.siteanalyser.configuration.configurationLanguage.impl.ConfigurationLanguagePackageImpl.init();

  /**
   * The meta object id for the '{@link de.tgremple.siteanalyser.configuration.configurationLanguage.impl.SiteStructureImpl <em>Site Structure</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.tgremple.siteanalyser.configuration.configurationLanguage.impl.SiteStructureImpl
   * @see de.tgremple.siteanalyser.configuration.configurationLanguage.impl.ConfigurationLanguagePackageImpl#getSiteStructure()
   * @generated
   */
  int SITE_STRUCTURE = 0;

  /**
   * The feature id for the '<em><b>Type Definitions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SITE_STRUCTURE__TYPE_DEFINITIONS = 0;

  /**
   * The number of structural features of the '<em>Site Structure</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SITE_STRUCTURE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link de.tgremple.siteanalyser.configuration.configurationLanguage.impl.TypeImpl <em>Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.tgremple.siteanalyser.configuration.configurationLanguage.impl.TypeImpl
   * @see de.tgremple.siteanalyser.configuration.configurationLanguage.impl.ConfigurationLanguagePackageImpl#getType()
   * @generated
   */
  int TYPE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE__NAME = 0;

  /**
   * The feature id for the '<em><b>Properties</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE__PROPERTIES = 1;

  /**
   * The number of structural features of the '<em>Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link de.tgremple.siteanalyser.configuration.configurationLanguage.impl.ContentTypeImpl <em>Content Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.tgremple.siteanalyser.configuration.configurationLanguage.impl.ContentTypeImpl
   * @see de.tgremple.siteanalyser.configuration.configurationLanguage.impl.ConfigurationLanguagePackageImpl#getContentType()
   * @generated
   */
  int CONTENT_TYPE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTENT_TYPE__NAME = TYPE__NAME;

  /**
   * The feature id for the '<em><b>Properties</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTENT_TYPE__PROPERTIES = TYPE__PROPERTIES;

  /**
   * The feature id for the '<em><b>Selector</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTENT_TYPE__SELECTOR = TYPE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Content Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTENT_TYPE_FEATURE_COUNT = TYPE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link de.tgremple.siteanalyser.configuration.configurationLanguage.impl.ReferenceTypeImpl <em>Reference Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.tgremple.siteanalyser.configuration.configurationLanguage.impl.ReferenceTypeImpl
   * @see de.tgremple.siteanalyser.configuration.configurationLanguage.impl.ConfigurationLanguagePackageImpl#getReferenceType()
   * @generated
   */
  int REFERENCE_TYPE = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCE_TYPE__NAME = TYPE__NAME;

  /**
   * The feature id for the '<em><b>Properties</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCE_TYPE__PROPERTIES = TYPE__PROPERTIES;

  /**
   * The feature id for the '<em><b>Selector</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCE_TYPE__SELECTOR = TYPE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Reference Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCE_TYPE_FEATURE_COUNT = TYPE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link de.tgremple.siteanalyser.configuration.configurationLanguage.impl.PageTypeImpl <em>Page Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.tgremple.siteanalyser.configuration.configurationLanguage.impl.PageTypeImpl
   * @see de.tgremple.siteanalyser.configuration.configurationLanguage.impl.ConfigurationLanguagePackageImpl#getPageType()
   * @generated
   */
  int PAGE_TYPE = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAGE_TYPE__NAME = TYPE__NAME;

  /**
   * The feature id for the '<em><b>Properties</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAGE_TYPE__PROPERTIES = TYPE__PROPERTIES;

  /**
   * The feature id for the '<em><b>Selector</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAGE_TYPE__SELECTOR = TYPE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Page Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAGE_TYPE_FEATURE_COUNT = TYPE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link de.tgremple.siteanalyser.configuration.configurationLanguage.impl.ContentSelectorImpl <em>Content Selector</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.tgremple.siteanalyser.configuration.configurationLanguage.impl.ContentSelectorImpl
   * @see de.tgremple.siteanalyser.configuration.configurationLanguage.impl.ConfigurationLanguagePackageImpl#getContentSelector()
   * @generated
   */
  int CONTENT_SELECTOR = 5;

  /**
   * The number of structural features of the '<em>Content Selector</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTENT_SELECTOR_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link de.tgremple.siteanalyser.configuration.configurationLanguage.impl.PageSelectorImpl <em>Page Selector</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.tgremple.siteanalyser.configuration.configurationLanguage.impl.PageSelectorImpl
   * @see de.tgremple.siteanalyser.configuration.configurationLanguage.impl.ConfigurationLanguagePackageImpl#getPageSelector()
   * @generated
   */
  int PAGE_SELECTOR = 6;

  /**
   * The feature id for the '<em><b>Definition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAGE_SELECTOR__DEFINITION = 0;

  /**
   * The number of structural features of the '<em>Page Selector</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAGE_SELECTOR_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link de.tgremple.siteanalyser.configuration.configurationLanguage.impl.CssSelectorImpl <em>Css Selector</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.tgremple.siteanalyser.configuration.configurationLanguage.impl.CssSelectorImpl
   * @see de.tgremple.siteanalyser.configuration.configurationLanguage.impl.ConfigurationLanguagePackageImpl#getCssSelector()
   * @generated
   */
  int CSS_SELECTOR = 7;

  /**
   * The feature id for the '<em><b>Definition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CSS_SELECTOR__DEFINITION = CONTENT_SELECTOR_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Css Selector</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CSS_SELECTOR_FEATURE_COUNT = CONTENT_SELECTOR_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link de.tgremple.siteanalyser.configuration.configurationLanguage.impl.UrlPatternSelectorImpl <em>Url Pattern Selector</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.tgremple.siteanalyser.configuration.configurationLanguage.impl.UrlPatternSelectorImpl
   * @see de.tgremple.siteanalyser.configuration.configurationLanguage.impl.ConfigurationLanguagePackageImpl#getUrlPatternSelector()
   * @generated
   */
  int URL_PATTERN_SELECTOR = 8;

  /**
   * The feature id for the '<em><b>Definition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int URL_PATTERN_SELECTOR__DEFINITION = PAGE_SELECTOR__DEFINITION;

  /**
   * The number of structural features of the '<em>Url Pattern Selector</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int URL_PATTERN_SELECTOR_FEATURE_COUNT = PAGE_SELECTOR_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link de.tgremple.siteanalyser.configuration.configurationLanguage.impl.PropertyImpl <em>Property</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.tgremple.siteanalyser.configuration.configurationLanguage.impl.PropertyImpl
   * @see de.tgremple.siteanalyser.configuration.configurationLanguage.impl.ConfigurationLanguagePackageImpl#getProperty()
   * @generated
   */
  int PROPERTY = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY__TYPE = 1;

  /**
   * The feature id for the '<em><b>Selector</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY__SELECTOR = 2;

  /**
   * The number of structural features of the '<em>Property</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_FEATURE_COUNT = 3;


  /**
   * Returns the meta object for class '{@link de.tgremple.siteanalyser.configuration.configurationLanguage.SiteStructure <em>Site Structure</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Site Structure</em>'.
   * @see de.tgremple.siteanalyser.configuration.configurationLanguage.SiteStructure
   * @generated
   */
  EClass getSiteStructure();

  /**
   * Returns the meta object for the containment reference list '{@link de.tgremple.siteanalyser.configuration.configurationLanguage.SiteStructure#getTypeDefinitions <em>Type Definitions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Type Definitions</em>'.
   * @see de.tgremple.siteanalyser.configuration.configurationLanguage.SiteStructure#getTypeDefinitions()
   * @see #getSiteStructure()
   * @generated
   */
  EReference getSiteStructure_TypeDefinitions();

  /**
   * Returns the meta object for class '{@link de.tgremple.siteanalyser.configuration.configurationLanguage.Type <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type</em>'.
   * @see de.tgremple.siteanalyser.configuration.configurationLanguage.Type
   * @generated
   */
  EClass getType();

  /**
   * Returns the meta object for the attribute '{@link de.tgremple.siteanalyser.configuration.configurationLanguage.Type#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see de.tgremple.siteanalyser.configuration.configurationLanguage.Type#getName()
   * @see #getType()
   * @generated
   */
  EAttribute getType_Name();

  /**
   * Returns the meta object for the containment reference list '{@link de.tgremple.siteanalyser.configuration.configurationLanguage.Type#getProperties <em>Properties</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Properties</em>'.
   * @see de.tgremple.siteanalyser.configuration.configurationLanguage.Type#getProperties()
   * @see #getType()
   * @generated
   */
  EReference getType_Properties();

  /**
   * Returns the meta object for class '{@link de.tgremple.siteanalyser.configuration.configurationLanguage.ContentType <em>Content Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Content Type</em>'.
   * @see de.tgremple.siteanalyser.configuration.configurationLanguage.ContentType
   * @generated
   */
  EClass getContentType();

  /**
   * Returns the meta object for the containment reference '{@link de.tgremple.siteanalyser.configuration.configurationLanguage.ContentType#getSelector <em>Selector</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Selector</em>'.
   * @see de.tgremple.siteanalyser.configuration.configurationLanguage.ContentType#getSelector()
   * @see #getContentType()
   * @generated
   */
  EReference getContentType_Selector();

  /**
   * Returns the meta object for class '{@link de.tgremple.siteanalyser.configuration.configurationLanguage.ReferenceType <em>Reference Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Reference Type</em>'.
   * @see de.tgremple.siteanalyser.configuration.configurationLanguage.ReferenceType
   * @generated
   */
  EClass getReferenceType();

  /**
   * Returns the meta object for the containment reference '{@link de.tgremple.siteanalyser.configuration.configurationLanguage.ReferenceType#getSelector <em>Selector</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Selector</em>'.
   * @see de.tgremple.siteanalyser.configuration.configurationLanguage.ReferenceType#getSelector()
   * @see #getReferenceType()
   * @generated
   */
  EReference getReferenceType_Selector();

  /**
   * Returns the meta object for class '{@link de.tgremple.siteanalyser.configuration.configurationLanguage.PageType <em>Page Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Page Type</em>'.
   * @see de.tgremple.siteanalyser.configuration.configurationLanguage.PageType
   * @generated
   */
  EClass getPageType();

  /**
   * Returns the meta object for the containment reference '{@link de.tgremple.siteanalyser.configuration.configurationLanguage.PageType#getSelector <em>Selector</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Selector</em>'.
   * @see de.tgremple.siteanalyser.configuration.configurationLanguage.PageType#getSelector()
   * @see #getPageType()
   * @generated
   */
  EReference getPageType_Selector();

  /**
   * Returns the meta object for class '{@link de.tgremple.siteanalyser.configuration.configurationLanguage.ContentSelector <em>Content Selector</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Content Selector</em>'.
   * @see de.tgremple.siteanalyser.configuration.configurationLanguage.ContentSelector
   * @generated
   */
  EClass getContentSelector();

  /**
   * Returns the meta object for class '{@link de.tgremple.siteanalyser.configuration.configurationLanguage.PageSelector <em>Page Selector</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Page Selector</em>'.
   * @see de.tgremple.siteanalyser.configuration.configurationLanguage.PageSelector
   * @generated
   */
  EClass getPageSelector();

  /**
   * Returns the meta object for the attribute '{@link de.tgremple.siteanalyser.configuration.configurationLanguage.PageSelector#getDefinition <em>Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Definition</em>'.
   * @see de.tgremple.siteanalyser.configuration.configurationLanguage.PageSelector#getDefinition()
   * @see #getPageSelector()
   * @generated
   */
  EAttribute getPageSelector_Definition();

  /**
   * Returns the meta object for class '{@link de.tgremple.siteanalyser.configuration.configurationLanguage.CssSelector <em>Css Selector</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Css Selector</em>'.
   * @see de.tgremple.siteanalyser.configuration.configurationLanguage.CssSelector
   * @generated
   */
  EClass getCssSelector();

  /**
   * Returns the meta object for class '{@link de.tgremple.siteanalyser.configuration.configurationLanguage.UrlPatternSelector <em>Url Pattern Selector</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Url Pattern Selector</em>'.
   * @see de.tgremple.siteanalyser.configuration.configurationLanguage.UrlPatternSelector
   * @generated
   */
  EClass getUrlPatternSelector();

  /**
   * Returns the meta object for class '{@link de.tgremple.siteanalyser.configuration.configurationLanguage.Property <em>Property</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Property</em>'.
   * @see de.tgremple.siteanalyser.configuration.configurationLanguage.Property
   * @generated
   */
  EClass getProperty();

  /**
   * Returns the meta object for the attribute '{@link de.tgremple.siteanalyser.configuration.configurationLanguage.Property#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see de.tgremple.siteanalyser.configuration.configurationLanguage.Property#getName()
   * @see #getProperty()
   * @generated
   */
  EAttribute getProperty_Name();

  /**
   * Returns the meta object for the reference '{@link de.tgremple.siteanalyser.configuration.configurationLanguage.Property#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Type</em>'.
   * @see de.tgremple.siteanalyser.configuration.configurationLanguage.Property#getType()
   * @see #getProperty()
   * @generated
   */
  EReference getProperty_Type();

  /**
   * Returns the meta object for the containment reference '{@link de.tgremple.siteanalyser.configuration.configurationLanguage.Property#getSelector <em>Selector</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Selector</em>'.
   * @see de.tgremple.siteanalyser.configuration.configurationLanguage.Property#getSelector()
   * @see #getProperty()
   * @generated
   */
  EReference getProperty_Selector();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  ConfigurationLanguageFactory getConfigurationLanguageFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link de.tgremple.siteanalyser.configuration.configurationLanguage.impl.SiteStructureImpl <em>Site Structure</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.tgremple.siteanalyser.configuration.configurationLanguage.impl.SiteStructureImpl
     * @see de.tgremple.siteanalyser.configuration.configurationLanguage.impl.ConfigurationLanguagePackageImpl#getSiteStructure()
     * @generated
     */
    EClass SITE_STRUCTURE = eINSTANCE.getSiteStructure();

    /**
     * The meta object literal for the '<em><b>Type Definitions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SITE_STRUCTURE__TYPE_DEFINITIONS = eINSTANCE.getSiteStructure_TypeDefinitions();

    /**
     * The meta object literal for the '{@link de.tgremple.siteanalyser.configuration.configurationLanguage.impl.TypeImpl <em>Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.tgremple.siteanalyser.configuration.configurationLanguage.impl.TypeImpl
     * @see de.tgremple.siteanalyser.configuration.configurationLanguage.impl.ConfigurationLanguagePackageImpl#getType()
     * @generated
     */
    EClass TYPE = eINSTANCE.getType();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPE__NAME = eINSTANCE.getType_Name();

    /**
     * The meta object literal for the '<em><b>Properties</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TYPE__PROPERTIES = eINSTANCE.getType_Properties();

    /**
     * The meta object literal for the '{@link de.tgremple.siteanalyser.configuration.configurationLanguage.impl.ContentTypeImpl <em>Content Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.tgremple.siteanalyser.configuration.configurationLanguage.impl.ContentTypeImpl
     * @see de.tgremple.siteanalyser.configuration.configurationLanguage.impl.ConfigurationLanguagePackageImpl#getContentType()
     * @generated
     */
    EClass CONTENT_TYPE = eINSTANCE.getContentType();

    /**
     * The meta object literal for the '<em><b>Selector</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTENT_TYPE__SELECTOR = eINSTANCE.getContentType_Selector();

    /**
     * The meta object literal for the '{@link de.tgremple.siteanalyser.configuration.configurationLanguage.impl.ReferenceTypeImpl <em>Reference Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.tgremple.siteanalyser.configuration.configurationLanguage.impl.ReferenceTypeImpl
     * @see de.tgremple.siteanalyser.configuration.configurationLanguage.impl.ConfigurationLanguagePackageImpl#getReferenceType()
     * @generated
     */
    EClass REFERENCE_TYPE = eINSTANCE.getReferenceType();

    /**
     * The meta object literal for the '<em><b>Selector</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REFERENCE_TYPE__SELECTOR = eINSTANCE.getReferenceType_Selector();

    /**
     * The meta object literal for the '{@link de.tgremple.siteanalyser.configuration.configurationLanguage.impl.PageTypeImpl <em>Page Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.tgremple.siteanalyser.configuration.configurationLanguage.impl.PageTypeImpl
     * @see de.tgremple.siteanalyser.configuration.configurationLanguage.impl.ConfigurationLanguagePackageImpl#getPageType()
     * @generated
     */
    EClass PAGE_TYPE = eINSTANCE.getPageType();

    /**
     * The meta object literal for the '<em><b>Selector</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PAGE_TYPE__SELECTOR = eINSTANCE.getPageType_Selector();

    /**
     * The meta object literal for the '{@link de.tgremple.siteanalyser.configuration.configurationLanguage.impl.ContentSelectorImpl <em>Content Selector</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.tgremple.siteanalyser.configuration.configurationLanguage.impl.ContentSelectorImpl
     * @see de.tgremple.siteanalyser.configuration.configurationLanguage.impl.ConfigurationLanguagePackageImpl#getContentSelector()
     * @generated
     */
    EClass CONTENT_SELECTOR = eINSTANCE.getContentSelector();

    /**
     * The meta object literal for the '{@link de.tgremple.siteanalyser.configuration.configurationLanguage.impl.PageSelectorImpl <em>Page Selector</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.tgremple.siteanalyser.configuration.configurationLanguage.impl.PageSelectorImpl
     * @see de.tgremple.siteanalyser.configuration.configurationLanguage.impl.ConfigurationLanguagePackageImpl#getPageSelector()
     * @generated
     */
    EClass PAGE_SELECTOR = eINSTANCE.getPageSelector();

    /**
     * The meta object literal for the '<em><b>Definition</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PAGE_SELECTOR__DEFINITION = eINSTANCE.getPageSelector_Definition();

    /**
     * The meta object literal for the '{@link de.tgremple.siteanalyser.configuration.configurationLanguage.impl.CssSelectorImpl <em>Css Selector</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.tgremple.siteanalyser.configuration.configurationLanguage.impl.CssSelectorImpl
     * @see de.tgremple.siteanalyser.configuration.configurationLanguage.impl.ConfigurationLanguagePackageImpl#getCssSelector()
     * @generated
     */
    EClass CSS_SELECTOR = eINSTANCE.getCssSelector();

    /**
     * The meta object literal for the '{@link de.tgremple.siteanalyser.configuration.configurationLanguage.impl.UrlPatternSelectorImpl <em>Url Pattern Selector</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.tgremple.siteanalyser.configuration.configurationLanguage.impl.UrlPatternSelectorImpl
     * @see de.tgremple.siteanalyser.configuration.configurationLanguage.impl.ConfigurationLanguagePackageImpl#getUrlPatternSelector()
     * @generated
     */
    EClass URL_PATTERN_SELECTOR = eINSTANCE.getUrlPatternSelector();

    /**
     * The meta object literal for the '{@link de.tgremple.siteanalyser.configuration.configurationLanguage.impl.PropertyImpl <em>Property</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.tgremple.siteanalyser.configuration.configurationLanguage.impl.PropertyImpl
     * @see de.tgremple.siteanalyser.configuration.configurationLanguage.impl.ConfigurationLanguagePackageImpl#getProperty()
     * @generated
     */
    EClass PROPERTY = eINSTANCE.getProperty();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROPERTY__NAME = eINSTANCE.getProperty_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROPERTY__TYPE = eINSTANCE.getProperty_Type();

    /**
     * The meta object literal for the '<em><b>Selector</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROPERTY__SELECTOR = eINSTANCE.getProperty_Selector();

  }

} //ConfigurationLanguagePackage
