/**
 * generated by Xtext 2.12.0
 */
package de.tgremple.siteanalyser.configuration.configurationLanguage;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see de.tgremple.siteanalyser.configuration.configurationLanguage.ConfigurationLanguagePackage
 * @generated
 */
public interface ConfigurationLanguageFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ConfigurationLanguageFactory eINSTANCE = de.tgremple.siteanalyser.configuration.configurationLanguage.impl.ConfigurationLanguageFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Site Structure</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Site Structure</em>'.
   * @generated
   */
  SiteStructure createSiteStructure();

  /**
   * Returns a new object of class '<em>Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Type</em>'.
   * @generated
   */
  Type createType();

  /**
   * Returns a new object of class '<em>Content Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Content Type</em>'.
   * @generated
   */
  ContentType createContentType();

  /**
   * Returns a new object of class '<em>Page Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Page Type</em>'.
   * @generated
   */
  PageType createPageType();

  /**
   * Returns a new object of class '<em>Content Selector</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Content Selector</em>'.
   * @generated
   */
  ContentSelector createContentSelector();

  /**
   * Returns a new object of class '<em>Page Selector</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Page Selector</em>'.
   * @generated
   */
  PageSelector createPageSelector();

  /**
   * Returns a new object of class '<em>Css Selector</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Css Selector</em>'.
   * @generated
   */
  CssSelector createCssSelector();

  /**
   * Returns a new object of class '<em>Url Pattern Selector</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Url Pattern Selector</em>'.
   * @generated
   */
  UrlPatternSelector createUrlPatternSelector();

  /**
   * Returns a new object of class '<em>Property</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Property</em>'.
   * @generated
   */
  Property createProperty();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  ConfigurationLanguagePackage getConfigurationLanguagePackage();

} //ConfigurationLanguageFactory
