/**
 * generated by Xtext 2.12.0
 */
package de.tgremple.siteanalyser.configuration.configurationLanguage;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Content Selector</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.tgremple.siteanalyser.configuration.configurationLanguage.ConfigurationLanguagePackage#getContentSelector()
 * @model
 * @generated
 */
public interface ContentSelector extends EObject
{
} // ContentSelector
