/**
 * generated by Xtext 2.12.0
 */
package de.tgremple.siteanalyser.configuration.configurationLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Css Selector</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.tgremple.siteanalyser.configuration.configurationLanguage.ConfigurationLanguagePackage#getCssSelector()
 * @model
 * @generated
 */
public interface CssSelector extends ContentSelector, PageSelector
{
} // CssSelector
