/**
 * generated by Xtext 2.12.0
 */
package de.tgremple.siteanalyser.configuration.configurationLanguage;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Page Selector</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.tgremple.siteanalyser.configuration.configurationLanguage.PageSelector#getDefinition <em>Definition</em>}</li>
 * </ul>
 *
 * @see de.tgremple.siteanalyser.configuration.configurationLanguage.ConfigurationLanguagePackage#getPageSelector()
 * @model
 * @generated
 */
public interface PageSelector extends EObject
{
  /**
   * Returns the value of the '<em><b>Definition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Definition</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Definition</em>' attribute.
   * @see #setDefinition(String)
   * @see de.tgremple.siteanalyser.configuration.configurationLanguage.ConfigurationLanguagePackage#getPageSelector_Definition()
   * @model
   * @generated
   */
  String getDefinition();

  /**
   * Sets the value of the '{@link de.tgremple.siteanalyser.configuration.configurationLanguage.PageSelector#getDefinition <em>Definition</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Definition</em>' attribute.
   * @see #getDefinition()
   * @generated
   */
  void setDefinition(String value);

} // PageSelector
