/**
 * generated by Xtext 2.12.0
 */
package de.tgremple.siteanalyser.configuration.configurationLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Page Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.tgremple.siteanalyser.configuration.configurationLanguage.PageType#getSelector <em>Selector</em>}</li>
 * </ul>
 *
 * @see de.tgremple.siteanalyser.configuration.configurationLanguage.ConfigurationLanguagePackage#getPageType()
 * @model
 * @generated
 */
public interface PageType extends Type
{
  /**
   * Returns the value of the '<em><b>Selector</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Selector</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Selector</em>' containment reference.
   * @see #setSelector(PageSelector)
   * @see de.tgremple.siteanalyser.configuration.configurationLanguage.ConfigurationLanguagePackage#getPageType_Selector()
   * @model containment="true"
   * @generated
   */
  PageSelector getSelector();

  /**
   * Sets the value of the '{@link de.tgremple.siteanalyser.configuration.configurationLanguage.PageType#getSelector <em>Selector</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Selector</em>' containment reference.
   * @see #getSelector()
   * @generated
   */
  void setSelector(PageSelector value);

} // PageType
