/**
 * generated by Xtext 2.12.0
 */
package de.tgremple.siteanalyser.configuration.configurationLanguage;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Property</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.tgremple.siteanalyser.configuration.configurationLanguage.Property#getName <em>Name</em>}</li>
 *   <li>{@link de.tgremple.siteanalyser.configuration.configurationLanguage.Property#getType <em>Type</em>}</li>
 *   <li>{@link de.tgremple.siteanalyser.configuration.configurationLanguage.Property#getSelector <em>Selector</em>}</li>
 * </ul>
 *
 * @see de.tgremple.siteanalyser.configuration.configurationLanguage.ConfigurationLanguagePackage#getProperty()
 * @model
 * @generated
 */
public interface Property extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see de.tgremple.siteanalyser.configuration.configurationLanguage.ConfigurationLanguagePackage#getProperty_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link de.tgremple.siteanalyser.configuration.configurationLanguage.Property#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' reference.
   * @see #setType(ContentType)
   * @see de.tgremple.siteanalyser.configuration.configurationLanguage.ConfigurationLanguagePackage#getProperty_Type()
   * @model
   * @generated
   */
  ContentType getType();

  /**
   * Sets the value of the '{@link de.tgremple.siteanalyser.configuration.configurationLanguage.Property#getType <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' reference.
   * @see #getType()
   * @generated
   */
  void setType(ContentType value);

  /**
   * Returns the value of the '<em><b>Selector</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Selector</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Selector</em>' containment reference.
   * @see #setSelector(ContentSelector)
   * @see de.tgremple.siteanalyser.configuration.configurationLanguage.ConfigurationLanguagePackage#getProperty_Selector()
   * @model containment="true"
   * @generated
   */
  ContentSelector getSelector();

  /**
   * Sets the value of the '{@link de.tgremple.siteanalyser.configuration.configurationLanguage.Property#getSelector <em>Selector</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Selector</em>' containment reference.
   * @see #getSelector()
   * @generated
   */
  void setSelector(ContentSelector value);

} // Property
