/**
 * generated by Xtext 2.12.0
 */
package de.tgremple.siteanalyser.configuration.configurationLanguage;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Site Structure</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.tgremple.siteanalyser.configuration.configurationLanguage.SiteStructure#getTypeDefinitions <em>Type Definitions</em>}</li>
 * </ul>
 *
 * @see de.tgremple.siteanalyser.configuration.configurationLanguage.ConfigurationLanguagePackage#getSiteStructure()
 * @model
 * @generated
 */
public interface SiteStructure extends EObject
{
  /**
   * Returns the value of the '<em><b>Type Definitions</b></em>' containment reference list.
   * The list contents are of type {@link de.tgremple.siteanalyser.configuration.configurationLanguage.Type}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type Definitions</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type Definitions</em>' containment reference list.
   * @see de.tgremple.siteanalyser.configuration.configurationLanguage.ConfigurationLanguagePackage#getSiteStructure_TypeDefinitions()
   * @model containment="true"
   * @generated
   */
  EList<Type> getTypeDefinitions();

} // SiteStructure
