/**
 * generated by Xtext 2.12.0
 */
package de.tgremple.siteanalyser.configuration.configurationLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Url Pattern Selector</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.tgremple.siteanalyser.configuration.configurationLanguage.ConfigurationLanguagePackage#getUrlPatternSelector()
 * @model
 * @generated
 */
public interface UrlPatternSelector extends PageSelector
{
} // UrlPatternSelector
