/**
 * generated by Xtext 2.12.0
 */
package de.tgremple.siteanalyser.configuration.tests;

import com.google.inject.Inject;
import de.tgremple.siteanalyser.configuration.configurationLanguage.SiteStructure;
import de.tgremple.siteanalyser.configuration.tests.ConfigurationLanguageInjectorProvider;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.XtextRunner;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(XtextRunner.class)
@InjectWith(ConfigurationLanguageInjectorProvider.class)
@SuppressWarnings("all")
public class ConfigurationLanguageParsingTest {
  @Inject
  private ParseHelper<SiteStructure> parseHelper;
  
  @Test
  public void loadModel() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("Hello Xtext!");
      _builder.newLine();
      final SiteStructure result = this.parseHelper.parse(_builder);
      Assert.assertNotNull(result);
      Assert.assertTrue(result.eResource().getErrors().isEmpty());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
