/*
 * generated by Xtext 2.12.0
 */
package de.tgremple.siteanalyser.configuration.idea.highlighting


class ConfigurationLanguageColorSettingsPage extends ConfigurationLanguageBaseColorSettingsPage {
}
