/*
 * generated by Xtext 2.12.0
 */
package de.tgremple.siteanalyser.configuration.idea.lang;

import com.intellij.psi.tree.IFileElementType;
import de.tgremple.siteanalyser.configuration.idea.lang.psi.impl.ConfigurationLanguageFileImpl;
import de.tgremple.siteanalyser.configuration.services.ConfigurationLanguageGrammarAccess;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.idea.lang.IElementTypeProvider;
import org.eclipse.xtext.psi.stubs.XtextFileElementType;
import org.eclipse.xtext.psi.stubs.XtextFileStub;
import org.eclipse.xtext.psi.tree.IGrammarAwareElementType;

public class ConfigurationLanguageElementTypeProvider implements IElementTypeProvider {

	public static final IFileElementType FILE_TYPE = new XtextFileElementType<XtextFileStub<ConfigurationLanguageFileImpl>>(ConfigurationLanguageLanguage.INSTANCE);

	private static final Map<EObject, IGrammarAwareElementType> GRAMMAR_ELEMENT_TYPE = new HashMap<EObject, IGrammarAwareElementType>();

	private static IGrammarAwareElementType associate(IGrammarAwareElementType grammarAwareElementType) {
		GRAMMAR_ELEMENT_TYPE.put(grammarAwareElementType.getGrammarElement(), grammarAwareElementType);
		return grammarAwareElementType;
	}

	private static final ConfigurationLanguageGrammarAccess GRAMMAR_ACCESS = ConfigurationLanguageLanguage.INSTANCE.getInstance(ConfigurationLanguageGrammarAccess.class);

	private static class SiteStructureFactory {
		public static IGrammarAwareElementType createSiteStructureElementType() {
			return new IGrammarAwareElementType("SiteStructure_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getSiteStructureRule());
		}
		public static IGrammarAwareElementType createSiteStructure_TypeDefinitionsAssignmentElementType() {
			return new IGrammarAwareElementType("SiteStructure_TypeDefinitionsAssignment_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getSiteStructureAccess().getTypeDefinitionsAssignment());
		}
		public static IGrammarAwareElementType createSiteStructure_TypeDefinitionsTypeParserRuleCall_0ElementType() {
			return new IGrammarAwareElementType("SiteStructure_TypeDefinitionsTypeParserRuleCall_0_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getSiteStructureAccess().getTypeDefinitionsTypeParserRuleCall_0());
		}
	}

	public static final IGrammarAwareElementType SiteStructure_ELEMENT_TYPE = associate(SiteStructureFactory.createSiteStructureElementType());

	public static final IGrammarAwareElementType SiteStructure_TypeDefinitionsAssignment_ELEMENT_TYPE = associate(SiteStructureFactory.createSiteStructure_TypeDefinitionsAssignmentElementType());

	public static final IGrammarAwareElementType SiteStructure_TypeDefinitionsTypeParserRuleCall_0_ELEMENT_TYPE = associate(SiteStructureFactory.createSiteStructure_TypeDefinitionsTypeParserRuleCall_0ElementType());

	private static class TypeFactory {
		public static IGrammarAwareElementType createTypeElementType() {
			return new IGrammarAwareElementType("Type_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getTypeRule());
		}
		public static IGrammarAwareElementType createType_AlternativesElementType() {
			return new IGrammarAwareElementType("Type_Alternatives_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getTypeAccess().getAlternatives());
		}
		public static IGrammarAwareElementType createType_ContentTypeParserRuleCall_0ElementType() {
			return new IGrammarAwareElementType("Type_ContentTypeParserRuleCall_0_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getTypeAccess().getContentTypeParserRuleCall_0());
		}
		public static IGrammarAwareElementType createType_PageTypeParserRuleCall_1ElementType() {
			return new IGrammarAwareElementType("Type_PageTypeParserRuleCall_1_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getTypeAccess().getPageTypeParserRuleCall_1());
		}
		public static IGrammarAwareElementType createType_ReferenceTypeParserRuleCall_2ElementType() {
			return new IGrammarAwareElementType("Type_ReferenceTypeParserRuleCall_2_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getTypeAccess().getReferenceTypeParserRuleCall_2());
		}
	}

	public static final IGrammarAwareElementType Type_ELEMENT_TYPE = associate(TypeFactory.createTypeElementType());

	public static final IGrammarAwareElementType Type_Alternatives_ELEMENT_TYPE = associate(TypeFactory.createType_AlternativesElementType());

	public static final IGrammarAwareElementType Type_ContentTypeParserRuleCall_0_ELEMENT_TYPE = associate(TypeFactory.createType_ContentTypeParserRuleCall_0ElementType());

	public static final IGrammarAwareElementType Type_PageTypeParserRuleCall_1_ELEMENT_TYPE = associate(TypeFactory.createType_PageTypeParserRuleCall_1ElementType());

	public static final IGrammarAwareElementType Type_ReferenceTypeParserRuleCall_2_ELEMENT_TYPE = associate(TypeFactory.createType_ReferenceTypeParserRuleCall_2ElementType());

	private static class ContentTypeFactory {
		public static IGrammarAwareElementType createContentTypeElementType() {
			return new IGrammarAwareElementType("ContentType_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getContentTypeRule());
		}
		public static IGrammarAwareElementType createContentType_GroupElementType() {
			return new IGrammarAwareElementType("ContentType_Group_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getContentTypeAccess().getGroup());
		}
		public static IGrammarAwareElementType createContentType_ContentKeyword_0ElementType() {
			return new IGrammarAwareElementType("ContentType_ContentKeyword_0_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getContentTypeAccess().getContentKeyword_0());
		}
		public static IGrammarAwareElementType createContentType_TypeKeyword_1ElementType() {
			return new IGrammarAwareElementType("ContentType_TypeKeyword_1_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getContentTypeAccess().getTypeKeyword_1());
		}
		public static IGrammarAwareElementType createContentType_NameAssignment_2ElementType() {
			return new IGrammarAwareElementType("ContentType_NameAssignment_2_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getContentTypeAccess().getNameAssignment_2());
		}
		public static IGrammarAwareElementType createContentType_NameIDTerminalRuleCall_2_0ElementType() {
			return new IGrammarAwareElementType("ContentType_NameIDTerminalRuleCall_2_0_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getContentTypeAccess().getNameIDTerminalRuleCall_2_0());
		}
		public static IGrammarAwareElementType createContentType_Group_3ElementType() {
			return new IGrammarAwareElementType("ContentType_Group_3_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getContentTypeAccess().getGroup_3());
		}
		public static IGrammarAwareElementType createContentType_IsKeyword_3_0ElementType() {
			return new IGrammarAwareElementType("ContentType_IsKeyword_3_0_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getContentTypeAccess().getIsKeyword_3_0());
		}
		public static IGrammarAwareElementType createContentType_RecognizedKeyword_3_1ElementType() {
			return new IGrammarAwareElementType("ContentType_RecognizedKeyword_3_1_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getContentTypeAccess().getRecognizedKeyword_3_1());
		}
		public static IGrammarAwareElementType createContentType_ByKeyword_3_2ElementType() {
			return new IGrammarAwareElementType("ContentType_ByKeyword_3_2_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getContentTypeAccess().getByKeyword_3_2());
		}
		public static IGrammarAwareElementType createContentType_SelectorAssignment_3_3ElementType() {
			return new IGrammarAwareElementType("ContentType_SelectorAssignment_3_3_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getContentTypeAccess().getSelectorAssignment_3_3());
		}
		public static IGrammarAwareElementType createContentType_SelectorContentSelectorParserRuleCall_3_3_0ElementType() {
			return new IGrammarAwareElementType("ContentType_SelectorContentSelectorParserRuleCall_3_3_0_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getContentTypeAccess().getSelectorContentSelectorParserRuleCall_3_3_0());
		}
		public static IGrammarAwareElementType createContentType_Group_4ElementType() {
			return new IGrammarAwareElementType("ContentType_Group_4_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getContentTypeAccess().getGroup_4());
		}
		public static IGrammarAwareElementType createContentType_RecognizeKeyword_4_0ElementType() {
			return new IGrammarAwareElementType("ContentType_RecognizeKeyword_4_0_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getContentTypeAccess().getRecognizeKeyword_4_0());
		}
		public static IGrammarAwareElementType createContentType_PropertiesAssignment_4_1ElementType() {
			return new IGrammarAwareElementType("ContentType_PropertiesAssignment_4_1_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getContentTypeAccess().getPropertiesAssignment_4_1());
		}
		public static IGrammarAwareElementType createContentType_PropertiesPropertyParserRuleCall_4_1_0ElementType() {
			return new IGrammarAwareElementType("ContentType_PropertiesPropertyParserRuleCall_4_1_0_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getContentTypeAccess().getPropertiesPropertyParserRuleCall_4_1_0());
		}
	}

	public static final IGrammarAwareElementType ContentType_ELEMENT_TYPE = associate(ContentTypeFactory.createContentTypeElementType());

	public static final IGrammarAwareElementType ContentType_Group_ELEMENT_TYPE = associate(ContentTypeFactory.createContentType_GroupElementType());

	public static final IGrammarAwareElementType ContentType_ContentKeyword_0_ELEMENT_TYPE = associate(ContentTypeFactory.createContentType_ContentKeyword_0ElementType());

	public static final IGrammarAwareElementType ContentType_TypeKeyword_1_ELEMENT_TYPE = associate(ContentTypeFactory.createContentType_TypeKeyword_1ElementType());

	public static final IGrammarAwareElementType ContentType_NameAssignment_2_ELEMENT_TYPE = associate(ContentTypeFactory.createContentType_NameAssignment_2ElementType());

	public static final IGrammarAwareElementType ContentType_NameIDTerminalRuleCall_2_0_ELEMENT_TYPE = associate(ContentTypeFactory.createContentType_NameIDTerminalRuleCall_2_0ElementType());

	public static final IGrammarAwareElementType ContentType_Group_3_ELEMENT_TYPE = associate(ContentTypeFactory.createContentType_Group_3ElementType());

	public static final IGrammarAwareElementType ContentType_IsKeyword_3_0_ELEMENT_TYPE = associate(ContentTypeFactory.createContentType_IsKeyword_3_0ElementType());

	public static final IGrammarAwareElementType ContentType_RecognizedKeyword_3_1_ELEMENT_TYPE = associate(ContentTypeFactory.createContentType_RecognizedKeyword_3_1ElementType());

	public static final IGrammarAwareElementType ContentType_ByKeyword_3_2_ELEMENT_TYPE = associate(ContentTypeFactory.createContentType_ByKeyword_3_2ElementType());

	public static final IGrammarAwareElementType ContentType_SelectorAssignment_3_3_ELEMENT_TYPE = associate(ContentTypeFactory.createContentType_SelectorAssignment_3_3ElementType());

	public static final IGrammarAwareElementType ContentType_SelectorContentSelectorParserRuleCall_3_3_0_ELEMENT_TYPE = associate(ContentTypeFactory.createContentType_SelectorContentSelectorParserRuleCall_3_3_0ElementType());

	public static final IGrammarAwareElementType ContentType_Group_4_ELEMENT_TYPE = associate(ContentTypeFactory.createContentType_Group_4ElementType());

	public static final IGrammarAwareElementType ContentType_RecognizeKeyword_4_0_ELEMENT_TYPE = associate(ContentTypeFactory.createContentType_RecognizeKeyword_4_0ElementType());

	public static final IGrammarAwareElementType ContentType_PropertiesAssignment_4_1_ELEMENT_TYPE = associate(ContentTypeFactory.createContentType_PropertiesAssignment_4_1ElementType());

	public static final IGrammarAwareElementType ContentType_PropertiesPropertyParserRuleCall_4_1_0_ELEMENT_TYPE = associate(ContentTypeFactory.createContentType_PropertiesPropertyParserRuleCall_4_1_0ElementType());

	private static class ReferenceTypeFactory {
		public static IGrammarAwareElementType createReferenceTypeElementType() {
			return new IGrammarAwareElementType("ReferenceType_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getReferenceTypeRule());
		}
		public static IGrammarAwareElementType createReferenceType_GroupElementType() {
			return new IGrammarAwareElementType("ReferenceType_Group_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getReferenceTypeAccess().getGroup());
		}
		public static IGrammarAwareElementType createReferenceType_ReferenceKeyword_0ElementType() {
			return new IGrammarAwareElementType("ReferenceType_ReferenceKeyword_0_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getReferenceTypeAccess().getReferenceKeyword_0());
		}
		public static IGrammarAwareElementType createReferenceType_TypeKeyword_1ElementType() {
			return new IGrammarAwareElementType("ReferenceType_TypeKeyword_1_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getReferenceTypeAccess().getTypeKeyword_1());
		}
		public static IGrammarAwareElementType createReferenceType_NameAssignment_2ElementType() {
			return new IGrammarAwareElementType("ReferenceType_NameAssignment_2_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getReferenceTypeAccess().getNameAssignment_2());
		}
		public static IGrammarAwareElementType createReferenceType_NameIDTerminalRuleCall_2_0ElementType() {
			return new IGrammarAwareElementType("ReferenceType_NameIDTerminalRuleCall_2_0_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getReferenceTypeAccess().getNameIDTerminalRuleCall_2_0());
		}
		public static IGrammarAwareElementType createReferenceType_Group_3ElementType() {
			return new IGrammarAwareElementType("ReferenceType_Group_3_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getReferenceTypeAccess().getGroup_3());
		}
		public static IGrammarAwareElementType createReferenceType_IsKeyword_3_0ElementType() {
			return new IGrammarAwareElementType("ReferenceType_IsKeyword_3_0_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getReferenceTypeAccess().getIsKeyword_3_0());
		}
		public static IGrammarAwareElementType createReferenceType_RecognizedKeyword_3_1ElementType() {
			return new IGrammarAwareElementType("ReferenceType_RecognizedKeyword_3_1_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getReferenceTypeAccess().getRecognizedKeyword_3_1());
		}
		public static IGrammarAwareElementType createReferenceType_ByKeyword_3_2ElementType() {
			return new IGrammarAwareElementType("ReferenceType_ByKeyword_3_2_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getReferenceTypeAccess().getByKeyword_3_2());
		}
		public static IGrammarAwareElementType createReferenceType_SelectorAssignment_3_3ElementType() {
			return new IGrammarAwareElementType("ReferenceType_SelectorAssignment_3_3_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getReferenceTypeAccess().getSelectorAssignment_3_3());
		}
		public static IGrammarAwareElementType createReferenceType_SelectorContentSelectorParserRuleCall_3_3_0ElementType() {
			return new IGrammarAwareElementType("ReferenceType_SelectorContentSelectorParserRuleCall_3_3_0_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getReferenceTypeAccess().getSelectorContentSelectorParserRuleCall_3_3_0());
		}
		public static IGrammarAwareElementType createReferenceType_Group_4ElementType() {
			return new IGrammarAwareElementType("ReferenceType_Group_4_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getReferenceTypeAccess().getGroup_4());
		}
		public static IGrammarAwareElementType createReferenceType_RecognizeKeyword_4_0ElementType() {
			return new IGrammarAwareElementType("ReferenceType_RecognizeKeyword_4_0_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getReferenceTypeAccess().getRecognizeKeyword_4_0());
		}
		public static IGrammarAwareElementType createReferenceType_PropertiesAssignment_4_1ElementType() {
			return new IGrammarAwareElementType("ReferenceType_PropertiesAssignment_4_1_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getReferenceTypeAccess().getPropertiesAssignment_4_1());
		}
		public static IGrammarAwareElementType createReferenceType_PropertiesPropertyParserRuleCall_4_1_0ElementType() {
			return new IGrammarAwareElementType("ReferenceType_PropertiesPropertyParserRuleCall_4_1_0_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getReferenceTypeAccess().getPropertiesPropertyParserRuleCall_4_1_0());
		}
	}

	public static final IGrammarAwareElementType ReferenceType_ELEMENT_TYPE = associate(ReferenceTypeFactory.createReferenceTypeElementType());

	public static final IGrammarAwareElementType ReferenceType_Group_ELEMENT_TYPE = associate(ReferenceTypeFactory.createReferenceType_GroupElementType());

	public static final IGrammarAwareElementType ReferenceType_ReferenceKeyword_0_ELEMENT_TYPE = associate(ReferenceTypeFactory.createReferenceType_ReferenceKeyword_0ElementType());

	public static final IGrammarAwareElementType ReferenceType_TypeKeyword_1_ELEMENT_TYPE = associate(ReferenceTypeFactory.createReferenceType_TypeKeyword_1ElementType());

	public static final IGrammarAwareElementType ReferenceType_NameAssignment_2_ELEMENT_TYPE = associate(ReferenceTypeFactory.createReferenceType_NameAssignment_2ElementType());

	public static final IGrammarAwareElementType ReferenceType_NameIDTerminalRuleCall_2_0_ELEMENT_TYPE = associate(ReferenceTypeFactory.createReferenceType_NameIDTerminalRuleCall_2_0ElementType());

	public static final IGrammarAwareElementType ReferenceType_Group_3_ELEMENT_TYPE = associate(ReferenceTypeFactory.createReferenceType_Group_3ElementType());

	public static final IGrammarAwareElementType ReferenceType_IsKeyword_3_0_ELEMENT_TYPE = associate(ReferenceTypeFactory.createReferenceType_IsKeyword_3_0ElementType());

	public static final IGrammarAwareElementType ReferenceType_RecognizedKeyword_3_1_ELEMENT_TYPE = associate(ReferenceTypeFactory.createReferenceType_RecognizedKeyword_3_1ElementType());

	public static final IGrammarAwareElementType ReferenceType_ByKeyword_3_2_ELEMENT_TYPE = associate(ReferenceTypeFactory.createReferenceType_ByKeyword_3_2ElementType());

	public static final IGrammarAwareElementType ReferenceType_SelectorAssignment_3_3_ELEMENT_TYPE = associate(ReferenceTypeFactory.createReferenceType_SelectorAssignment_3_3ElementType());

	public static final IGrammarAwareElementType ReferenceType_SelectorContentSelectorParserRuleCall_3_3_0_ELEMENT_TYPE = associate(ReferenceTypeFactory.createReferenceType_SelectorContentSelectorParserRuleCall_3_3_0ElementType());

	public static final IGrammarAwareElementType ReferenceType_Group_4_ELEMENT_TYPE = associate(ReferenceTypeFactory.createReferenceType_Group_4ElementType());

	public static final IGrammarAwareElementType ReferenceType_RecognizeKeyword_4_0_ELEMENT_TYPE = associate(ReferenceTypeFactory.createReferenceType_RecognizeKeyword_4_0ElementType());

	public static final IGrammarAwareElementType ReferenceType_PropertiesAssignment_4_1_ELEMENT_TYPE = associate(ReferenceTypeFactory.createReferenceType_PropertiesAssignment_4_1ElementType());

	public static final IGrammarAwareElementType ReferenceType_PropertiesPropertyParserRuleCall_4_1_0_ELEMENT_TYPE = associate(ReferenceTypeFactory.createReferenceType_PropertiesPropertyParserRuleCall_4_1_0ElementType());

	private static class PageTypeFactory {
		public static IGrammarAwareElementType createPageTypeElementType() {
			return new IGrammarAwareElementType("PageType_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getPageTypeRule());
		}
		public static IGrammarAwareElementType createPageType_GroupElementType() {
			return new IGrammarAwareElementType("PageType_Group_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getPageTypeAccess().getGroup());
		}
		public static IGrammarAwareElementType createPageType_PageKeyword_0ElementType() {
			return new IGrammarAwareElementType("PageType_PageKeyword_0_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getPageTypeAccess().getPageKeyword_0());
		}
		public static IGrammarAwareElementType createPageType_TypeKeyword_1ElementType() {
			return new IGrammarAwareElementType("PageType_TypeKeyword_1_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getPageTypeAccess().getTypeKeyword_1());
		}
		public static IGrammarAwareElementType createPageType_NameAssignment_2ElementType() {
			return new IGrammarAwareElementType("PageType_NameAssignment_2_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getPageTypeAccess().getNameAssignment_2());
		}
		public static IGrammarAwareElementType createPageType_NameIDTerminalRuleCall_2_0ElementType() {
			return new IGrammarAwareElementType("PageType_NameIDTerminalRuleCall_2_0_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getPageTypeAccess().getNameIDTerminalRuleCall_2_0());
		}
		public static IGrammarAwareElementType createPageType_IsKeyword_3ElementType() {
			return new IGrammarAwareElementType("PageType_IsKeyword_3_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getPageTypeAccess().getIsKeyword_3());
		}
		public static IGrammarAwareElementType createPageType_RecognizedKeyword_4ElementType() {
			return new IGrammarAwareElementType("PageType_RecognizedKeyword_4_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getPageTypeAccess().getRecognizedKeyword_4());
		}
		public static IGrammarAwareElementType createPageType_ByKeyword_5ElementType() {
			return new IGrammarAwareElementType("PageType_ByKeyword_5_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getPageTypeAccess().getByKeyword_5());
		}
		public static IGrammarAwareElementType createPageType_SelectorAssignment_6ElementType() {
			return new IGrammarAwareElementType("PageType_SelectorAssignment_6_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getPageTypeAccess().getSelectorAssignment_6());
		}
		public static IGrammarAwareElementType createPageType_SelectorPageSelectorParserRuleCall_6_0ElementType() {
			return new IGrammarAwareElementType("PageType_SelectorPageSelectorParserRuleCall_6_0_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getPageTypeAccess().getSelectorPageSelectorParserRuleCall_6_0());
		}
		public static IGrammarAwareElementType createPageType_Group_7ElementType() {
			return new IGrammarAwareElementType("PageType_Group_7_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getPageTypeAccess().getGroup_7());
		}
		public static IGrammarAwareElementType createPageType_RecognizeKeyword_7_0ElementType() {
			return new IGrammarAwareElementType("PageType_RecognizeKeyword_7_0_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getPageTypeAccess().getRecognizeKeyword_7_0());
		}
		public static IGrammarAwareElementType createPageType_PropertiesAssignment_7_1ElementType() {
			return new IGrammarAwareElementType("PageType_PropertiesAssignment_7_1_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getPageTypeAccess().getPropertiesAssignment_7_1());
		}
		public static IGrammarAwareElementType createPageType_PropertiesPropertyParserRuleCall_7_1_0ElementType() {
			return new IGrammarAwareElementType("PageType_PropertiesPropertyParserRuleCall_7_1_0_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getPageTypeAccess().getPropertiesPropertyParserRuleCall_7_1_0());
		}
	}

	public static final IGrammarAwareElementType PageType_ELEMENT_TYPE = associate(PageTypeFactory.createPageTypeElementType());

	public static final IGrammarAwareElementType PageType_Group_ELEMENT_TYPE = associate(PageTypeFactory.createPageType_GroupElementType());

	public static final IGrammarAwareElementType PageType_PageKeyword_0_ELEMENT_TYPE = associate(PageTypeFactory.createPageType_PageKeyword_0ElementType());

	public static final IGrammarAwareElementType PageType_TypeKeyword_1_ELEMENT_TYPE = associate(PageTypeFactory.createPageType_TypeKeyword_1ElementType());

	public static final IGrammarAwareElementType PageType_NameAssignment_2_ELEMENT_TYPE = associate(PageTypeFactory.createPageType_NameAssignment_2ElementType());

	public static final IGrammarAwareElementType PageType_NameIDTerminalRuleCall_2_0_ELEMENT_TYPE = associate(PageTypeFactory.createPageType_NameIDTerminalRuleCall_2_0ElementType());

	public static final IGrammarAwareElementType PageType_IsKeyword_3_ELEMENT_TYPE = associate(PageTypeFactory.createPageType_IsKeyword_3ElementType());

	public static final IGrammarAwareElementType PageType_RecognizedKeyword_4_ELEMENT_TYPE = associate(PageTypeFactory.createPageType_RecognizedKeyword_4ElementType());

	public static final IGrammarAwareElementType PageType_ByKeyword_5_ELEMENT_TYPE = associate(PageTypeFactory.createPageType_ByKeyword_5ElementType());

	public static final IGrammarAwareElementType PageType_SelectorAssignment_6_ELEMENT_TYPE = associate(PageTypeFactory.createPageType_SelectorAssignment_6ElementType());

	public static final IGrammarAwareElementType PageType_SelectorPageSelectorParserRuleCall_6_0_ELEMENT_TYPE = associate(PageTypeFactory.createPageType_SelectorPageSelectorParserRuleCall_6_0ElementType());

	public static final IGrammarAwareElementType PageType_Group_7_ELEMENT_TYPE = associate(PageTypeFactory.createPageType_Group_7ElementType());

	public static final IGrammarAwareElementType PageType_RecognizeKeyword_7_0_ELEMENT_TYPE = associate(PageTypeFactory.createPageType_RecognizeKeyword_7_0ElementType());

	public static final IGrammarAwareElementType PageType_PropertiesAssignment_7_1_ELEMENT_TYPE = associate(PageTypeFactory.createPageType_PropertiesAssignment_7_1ElementType());

	public static final IGrammarAwareElementType PageType_PropertiesPropertyParserRuleCall_7_1_0_ELEMENT_TYPE = associate(PageTypeFactory.createPageType_PropertiesPropertyParserRuleCall_7_1_0ElementType());

	private static class ContentSelectorFactory {
		public static IGrammarAwareElementType createContentSelectorElementType() {
			return new IGrammarAwareElementType("ContentSelector_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getContentSelectorRule());
		}
		public static IGrammarAwareElementType createContentSelector_CssSelectorParserRuleCallElementType() {
			return new IGrammarAwareElementType("ContentSelector_CssSelectorParserRuleCall_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getContentSelectorAccess().getCssSelectorParserRuleCall());
		}
	}

	public static final IGrammarAwareElementType ContentSelector_ELEMENT_TYPE = associate(ContentSelectorFactory.createContentSelectorElementType());

	public static final IGrammarAwareElementType ContentSelector_CssSelectorParserRuleCall_ELEMENT_TYPE = associate(ContentSelectorFactory.createContentSelector_CssSelectorParserRuleCallElementType());

	private static class PageSelectorFactory {
		public static IGrammarAwareElementType createPageSelectorElementType() {
			return new IGrammarAwareElementType("PageSelector_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getPageSelectorRule());
		}
		public static IGrammarAwareElementType createPageSelector_AlternativesElementType() {
			return new IGrammarAwareElementType("PageSelector_Alternatives_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getPageSelectorAccess().getAlternatives());
		}
		public static IGrammarAwareElementType createPageSelector_CssSelectorParserRuleCall_0ElementType() {
			return new IGrammarAwareElementType("PageSelector_CssSelectorParserRuleCall_0_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getPageSelectorAccess().getCssSelectorParserRuleCall_0());
		}
		public static IGrammarAwareElementType createPageSelector_UrlPatternSelectorParserRuleCall_1ElementType() {
			return new IGrammarAwareElementType("PageSelector_UrlPatternSelectorParserRuleCall_1_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getPageSelectorAccess().getUrlPatternSelectorParserRuleCall_1());
		}
	}

	public static final IGrammarAwareElementType PageSelector_ELEMENT_TYPE = associate(PageSelectorFactory.createPageSelectorElementType());

	public static final IGrammarAwareElementType PageSelector_Alternatives_ELEMENT_TYPE = associate(PageSelectorFactory.createPageSelector_AlternativesElementType());

	public static final IGrammarAwareElementType PageSelector_CssSelectorParserRuleCall_0_ELEMENT_TYPE = associate(PageSelectorFactory.createPageSelector_CssSelectorParserRuleCall_0ElementType());

	public static final IGrammarAwareElementType PageSelector_UrlPatternSelectorParserRuleCall_1_ELEMENT_TYPE = associate(PageSelectorFactory.createPageSelector_UrlPatternSelectorParserRuleCall_1ElementType());

	private static class CssSelectorFactory {
		public static IGrammarAwareElementType createCssSelectorElementType() {
			return new IGrammarAwareElementType("CssSelector_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getCssSelectorRule());
		}
		public static IGrammarAwareElementType createCssSelector_GroupElementType() {
			return new IGrammarAwareElementType("CssSelector_Group_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getCssSelectorAccess().getGroup());
		}
		public static IGrammarAwareElementType createCssSelector_CssKeyword_0ElementType() {
			return new IGrammarAwareElementType("CssSelector_CssKeyword_0_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getCssSelectorAccess().getCssKeyword_0());
		}
		public static IGrammarAwareElementType createCssSelector_DefinitionAssignment_1ElementType() {
			return new IGrammarAwareElementType("CssSelector_DefinitionAssignment_1_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getCssSelectorAccess().getDefinitionAssignment_1());
		}
		public static IGrammarAwareElementType createCssSelector_DefinitionSTRINGTerminalRuleCall_1_0ElementType() {
			return new IGrammarAwareElementType("CssSelector_DefinitionSTRINGTerminalRuleCall_1_0_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getCssSelectorAccess().getDefinitionSTRINGTerminalRuleCall_1_0());
		}
	}

	public static final IGrammarAwareElementType CssSelector_ELEMENT_TYPE = associate(CssSelectorFactory.createCssSelectorElementType());

	public static final IGrammarAwareElementType CssSelector_Group_ELEMENT_TYPE = associate(CssSelectorFactory.createCssSelector_GroupElementType());

	public static final IGrammarAwareElementType CssSelector_CssKeyword_0_ELEMENT_TYPE = associate(CssSelectorFactory.createCssSelector_CssKeyword_0ElementType());

	public static final IGrammarAwareElementType CssSelector_DefinitionAssignment_1_ELEMENT_TYPE = associate(CssSelectorFactory.createCssSelector_DefinitionAssignment_1ElementType());

	public static final IGrammarAwareElementType CssSelector_DefinitionSTRINGTerminalRuleCall_1_0_ELEMENT_TYPE = associate(CssSelectorFactory.createCssSelector_DefinitionSTRINGTerminalRuleCall_1_0ElementType());

	private static class UrlPatternSelectorFactory {
		public static IGrammarAwareElementType createUrlPatternSelectorElementType() {
			return new IGrammarAwareElementType("UrlPatternSelector_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getUrlPatternSelectorRule());
		}
		public static IGrammarAwareElementType createUrlPatternSelector_GroupElementType() {
			return new IGrammarAwareElementType("UrlPatternSelector_Group_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getUrlPatternSelectorAccess().getGroup());
		}
		public static IGrammarAwareElementType createUrlPatternSelector_UrlKeyword_0ElementType() {
			return new IGrammarAwareElementType("UrlPatternSelector_UrlKeyword_0_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getUrlPatternSelectorAccess().getUrlKeyword_0());
		}
		public static IGrammarAwareElementType createUrlPatternSelector_PatternKeyword_1ElementType() {
			return new IGrammarAwareElementType("UrlPatternSelector_PatternKeyword_1_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getUrlPatternSelectorAccess().getPatternKeyword_1());
		}
		public static IGrammarAwareElementType createUrlPatternSelector_DefinitionAssignment_2ElementType() {
			return new IGrammarAwareElementType("UrlPatternSelector_DefinitionAssignment_2_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getUrlPatternSelectorAccess().getDefinitionAssignment_2());
		}
		public static IGrammarAwareElementType createUrlPatternSelector_DefinitionSTRINGTerminalRuleCall_2_0ElementType() {
			return new IGrammarAwareElementType("UrlPatternSelector_DefinitionSTRINGTerminalRuleCall_2_0_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getUrlPatternSelectorAccess().getDefinitionSTRINGTerminalRuleCall_2_0());
		}
	}

	public static final IGrammarAwareElementType UrlPatternSelector_ELEMENT_TYPE = associate(UrlPatternSelectorFactory.createUrlPatternSelectorElementType());

	public static final IGrammarAwareElementType UrlPatternSelector_Group_ELEMENT_TYPE = associate(UrlPatternSelectorFactory.createUrlPatternSelector_GroupElementType());

	public static final IGrammarAwareElementType UrlPatternSelector_UrlKeyword_0_ELEMENT_TYPE = associate(UrlPatternSelectorFactory.createUrlPatternSelector_UrlKeyword_0ElementType());

	public static final IGrammarAwareElementType UrlPatternSelector_PatternKeyword_1_ELEMENT_TYPE = associate(UrlPatternSelectorFactory.createUrlPatternSelector_PatternKeyword_1ElementType());

	public static final IGrammarAwareElementType UrlPatternSelector_DefinitionAssignment_2_ELEMENT_TYPE = associate(UrlPatternSelectorFactory.createUrlPatternSelector_DefinitionAssignment_2ElementType());

	public static final IGrammarAwareElementType UrlPatternSelector_DefinitionSTRINGTerminalRuleCall_2_0_ELEMENT_TYPE = associate(UrlPatternSelectorFactory.createUrlPatternSelector_DefinitionSTRINGTerminalRuleCall_2_0ElementType());

	private static class PropertyFactory {
		public static IGrammarAwareElementType createPropertyElementType() {
			return new IGrammarAwareElementType("Property_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getPropertyRule());
		}
		public static IGrammarAwareElementType createProperty_GroupElementType() {
			return new IGrammarAwareElementType("Property_Group_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getPropertyAccess().getGroup());
		}
		public static IGrammarAwareElementType createProperty_NameAssignment_0ElementType() {
			return new IGrammarAwareElementType("Property_NameAssignment_0_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getPropertyAccess().getNameAssignment_0());
		}
		public static IGrammarAwareElementType createProperty_NameIDTerminalRuleCall_0_0ElementType() {
			return new IGrammarAwareElementType("Property_NameIDTerminalRuleCall_0_0_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getPropertyAccess().getNameIDTerminalRuleCall_0_0());
		}
		public static IGrammarAwareElementType createProperty_AsKeyword_1ElementType() {
			return new IGrammarAwareElementType("Property_AsKeyword_1_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getPropertyAccess().getAsKeyword_1());
		}
		public static IGrammarAwareElementType createProperty_TypeAssignment_2ElementType() {
			return new IGrammarAwareElementType("Property_TypeAssignment_2_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getPropertyAccess().getTypeAssignment_2());
		}
		public static IGrammarAwareElementType createProperty_TypeContentTypeCrossReference_2_0ElementType() {
			return new IGrammarAwareElementType("Property_TypeContentTypeCrossReference_2_0_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getPropertyAccess().getTypeContentTypeCrossReference_2_0());
		}
		public static IGrammarAwareElementType createProperty_TypeContentTypeIDTerminalRuleCall_2_0_1ElementType() {
			return new IGrammarAwareElementType("Property_TypeContentTypeIDTerminalRuleCall_2_0_1_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getPropertyAccess().getTypeContentTypeIDTerminalRuleCall_2_0_1());
		}
		public static IGrammarAwareElementType createProperty_Group_3ElementType() {
			return new IGrammarAwareElementType("Property_Group_3_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getPropertyAccess().getGroup_3());
		}
		public static IGrammarAwareElementType createProperty_ByKeyword_3_0ElementType() {
			return new IGrammarAwareElementType("Property_ByKeyword_3_0_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getPropertyAccess().getByKeyword_3_0());
		}
		public static IGrammarAwareElementType createProperty_SelectorAssignment_3_1ElementType() {
			return new IGrammarAwareElementType("Property_SelectorAssignment_3_1_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getPropertyAccess().getSelectorAssignment_3_1());
		}
		public static IGrammarAwareElementType createProperty_SelectorContentSelectorParserRuleCall_3_1_0ElementType() {
			return new IGrammarAwareElementType("Property_SelectorContentSelectorParserRuleCall_3_1_0_ELEMENT_TYPE", ConfigurationLanguageLanguage.INSTANCE, GRAMMAR_ACCESS.getPropertyAccess().getSelectorContentSelectorParserRuleCall_3_1_0());
		}
	}

	public static final IGrammarAwareElementType Property_ELEMENT_TYPE = associate(PropertyFactory.createPropertyElementType());

	public static final IGrammarAwareElementType Property_Group_ELEMENT_TYPE = associate(PropertyFactory.createProperty_GroupElementType());

	public static final IGrammarAwareElementType Property_NameAssignment_0_ELEMENT_TYPE = associate(PropertyFactory.createProperty_NameAssignment_0ElementType());

	public static final IGrammarAwareElementType Property_NameIDTerminalRuleCall_0_0_ELEMENT_TYPE = associate(PropertyFactory.createProperty_NameIDTerminalRuleCall_0_0ElementType());

	public static final IGrammarAwareElementType Property_AsKeyword_1_ELEMENT_TYPE = associate(PropertyFactory.createProperty_AsKeyword_1ElementType());

	public static final IGrammarAwareElementType Property_TypeAssignment_2_ELEMENT_TYPE = associate(PropertyFactory.createProperty_TypeAssignment_2ElementType());

	public static final IGrammarAwareElementType Property_TypeContentTypeCrossReference_2_0_ELEMENT_TYPE = associate(PropertyFactory.createProperty_TypeContentTypeCrossReference_2_0ElementType());

	public static final IGrammarAwareElementType Property_TypeContentTypeIDTerminalRuleCall_2_0_1_ELEMENT_TYPE = associate(PropertyFactory.createProperty_TypeContentTypeIDTerminalRuleCall_2_0_1ElementType());

	public static final IGrammarAwareElementType Property_Group_3_ELEMENT_TYPE = associate(PropertyFactory.createProperty_Group_3ElementType());

	public static final IGrammarAwareElementType Property_ByKeyword_3_0_ELEMENT_TYPE = associate(PropertyFactory.createProperty_ByKeyword_3_0ElementType());

	public static final IGrammarAwareElementType Property_SelectorAssignment_3_1_ELEMENT_TYPE = associate(PropertyFactory.createProperty_SelectorAssignment_3_1ElementType());

	public static final IGrammarAwareElementType Property_SelectorContentSelectorParserRuleCall_3_1_0_ELEMENT_TYPE = associate(PropertyFactory.createProperty_SelectorContentSelectorParserRuleCall_3_1_0ElementType());

	@Override
	public IFileElementType getFileType() {
		return FILE_TYPE;
	}

	@Override
	public IGrammarAwareElementType findElementType(EObject grammarElement) {
		return GRAMMAR_ELEMENT_TYPE.get(grammarElement);
	}
	
	public IGrammarAwareElementType getSiteStructureElementType() {
		return SiteStructure_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getSiteStructure_TypeDefinitionsAssignmentElementType() {
		return SiteStructure_TypeDefinitionsAssignment_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getSiteStructure_TypeDefinitionsTypeParserRuleCall_0ElementType() {
		return SiteStructure_TypeDefinitionsTypeParserRuleCall_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getTypeElementType() {
		return Type_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getType_AlternativesElementType() {
		return Type_Alternatives_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getType_ContentTypeParserRuleCall_0ElementType() {
		return Type_ContentTypeParserRuleCall_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getType_PageTypeParserRuleCall_1ElementType() {
		return Type_PageTypeParserRuleCall_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getType_ReferenceTypeParserRuleCall_2ElementType() {
		return Type_ReferenceTypeParserRuleCall_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getContentTypeElementType() {
		return ContentType_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getContentType_GroupElementType() {
		return ContentType_Group_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getContentType_ContentKeyword_0ElementType() {
		return ContentType_ContentKeyword_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getContentType_TypeKeyword_1ElementType() {
		return ContentType_TypeKeyword_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getContentType_NameAssignment_2ElementType() {
		return ContentType_NameAssignment_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getContentType_NameIDTerminalRuleCall_2_0ElementType() {
		return ContentType_NameIDTerminalRuleCall_2_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getContentType_Group_3ElementType() {
		return ContentType_Group_3_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getContentType_IsKeyword_3_0ElementType() {
		return ContentType_IsKeyword_3_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getContentType_RecognizedKeyword_3_1ElementType() {
		return ContentType_RecognizedKeyword_3_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getContentType_ByKeyword_3_2ElementType() {
		return ContentType_ByKeyword_3_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getContentType_SelectorAssignment_3_3ElementType() {
		return ContentType_SelectorAssignment_3_3_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getContentType_SelectorContentSelectorParserRuleCall_3_3_0ElementType() {
		return ContentType_SelectorContentSelectorParserRuleCall_3_3_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getContentType_Group_4ElementType() {
		return ContentType_Group_4_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getContentType_RecognizeKeyword_4_0ElementType() {
		return ContentType_RecognizeKeyword_4_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getContentType_PropertiesAssignment_4_1ElementType() {
		return ContentType_PropertiesAssignment_4_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getContentType_PropertiesPropertyParserRuleCall_4_1_0ElementType() {
		return ContentType_PropertiesPropertyParserRuleCall_4_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getReferenceTypeElementType() {
		return ReferenceType_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getReferenceType_GroupElementType() {
		return ReferenceType_Group_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getReferenceType_ReferenceKeyword_0ElementType() {
		return ReferenceType_ReferenceKeyword_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getReferenceType_TypeKeyword_1ElementType() {
		return ReferenceType_TypeKeyword_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getReferenceType_NameAssignment_2ElementType() {
		return ReferenceType_NameAssignment_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getReferenceType_NameIDTerminalRuleCall_2_0ElementType() {
		return ReferenceType_NameIDTerminalRuleCall_2_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getReferenceType_Group_3ElementType() {
		return ReferenceType_Group_3_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getReferenceType_IsKeyword_3_0ElementType() {
		return ReferenceType_IsKeyword_3_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getReferenceType_RecognizedKeyword_3_1ElementType() {
		return ReferenceType_RecognizedKeyword_3_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getReferenceType_ByKeyword_3_2ElementType() {
		return ReferenceType_ByKeyword_3_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getReferenceType_SelectorAssignment_3_3ElementType() {
		return ReferenceType_SelectorAssignment_3_3_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getReferenceType_SelectorContentSelectorParserRuleCall_3_3_0ElementType() {
		return ReferenceType_SelectorContentSelectorParserRuleCall_3_3_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getReferenceType_Group_4ElementType() {
		return ReferenceType_Group_4_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getReferenceType_RecognizeKeyword_4_0ElementType() {
		return ReferenceType_RecognizeKeyword_4_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getReferenceType_PropertiesAssignment_4_1ElementType() {
		return ReferenceType_PropertiesAssignment_4_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getReferenceType_PropertiesPropertyParserRuleCall_4_1_0ElementType() {
		return ReferenceType_PropertiesPropertyParserRuleCall_4_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPageTypeElementType() {
		return PageType_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPageType_GroupElementType() {
		return PageType_Group_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPageType_PageKeyword_0ElementType() {
		return PageType_PageKeyword_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPageType_TypeKeyword_1ElementType() {
		return PageType_TypeKeyword_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPageType_NameAssignment_2ElementType() {
		return PageType_NameAssignment_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPageType_NameIDTerminalRuleCall_2_0ElementType() {
		return PageType_NameIDTerminalRuleCall_2_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPageType_IsKeyword_3ElementType() {
		return PageType_IsKeyword_3_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPageType_RecognizedKeyword_4ElementType() {
		return PageType_RecognizedKeyword_4_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPageType_ByKeyword_5ElementType() {
		return PageType_ByKeyword_5_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPageType_SelectorAssignment_6ElementType() {
		return PageType_SelectorAssignment_6_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPageType_SelectorPageSelectorParserRuleCall_6_0ElementType() {
		return PageType_SelectorPageSelectorParserRuleCall_6_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPageType_Group_7ElementType() {
		return PageType_Group_7_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPageType_RecognizeKeyword_7_0ElementType() {
		return PageType_RecognizeKeyword_7_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPageType_PropertiesAssignment_7_1ElementType() {
		return PageType_PropertiesAssignment_7_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPageType_PropertiesPropertyParserRuleCall_7_1_0ElementType() {
		return PageType_PropertiesPropertyParserRuleCall_7_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getContentSelectorElementType() {
		return ContentSelector_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getContentSelector_CssSelectorParserRuleCallElementType() {
		return ContentSelector_CssSelectorParserRuleCall_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPageSelectorElementType() {
		return PageSelector_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPageSelector_AlternativesElementType() {
		return PageSelector_Alternatives_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPageSelector_CssSelectorParserRuleCall_0ElementType() {
		return PageSelector_CssSelectorParserRuleCall_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPageSelector_UrlPatternSelectorParserRuleCall_1ElementType() {
		return PageSelector_UrlPatternSelectorParserRuleCall_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getCssSelectorElementType() {
		return CssSelector_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getCssSelector_GroupElementType() {
		return CssSelector_Group_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getCssSelector_CssKeyword_0ElementType() {
		return CssSelector_CssKeyword_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getCssSelector_DefinitionAssignment_1ElementType() {
		return CssSelector_DefinitionAssignment_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getCssSelector_DefinitionSTRINGTerminalRuleCall_1_0ElementType() {
		return CssSelector_DefinitionSTRINGTerminalRuleCall_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getUrlPatternSelectorElementType() {
		return UrlPatternSelector_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getUrlPatternSelector_GroupElementType() {
		return UrlPatternSelector_Group_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getUrlPatternSelector_UrlKeyword_0ElementType() {
		return UrlPatternSelector_UrlKeyword_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getUrlPatternSelector_PatternKeyword_1ElementType() {
		return UrlPatternSelector_PatternKeyword_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getUrlPatternSelector_DefinitionAssignment_2ElementType() {
		return UrlPatternSelector_DefinitionAssignment_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getUrlPatternSelector_DefinitionSTRINGTerminalRuleCall_2_0ElementType() {
		return UrlPatternSelector_DefinitionSTRINGTerminalRuleCall_2_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPropertyElementType() {
		return Property_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getProperty_GroupElementType() {
		return Property_Group_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getProperty_NameAssignment_0ElementType() {
		return Property_NameAssignment_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getProperty_NameIDTerminalRuleCall_0_0ElementType() {
		return Property_NameIDTerminalRuleCall_0_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getProperty_AsKeyword_1ElementType() {
		return Property_AsKeyword_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getProperty_TypeAssignment_2ElementType() {
		return Property_TypeAssignment_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getProperty_TypeContentTypeCrossReference_2_0ElementType() {
		return Property_TypeContentTypeCrossReference_2_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getProperty_TypeContentTypeIDTerminalRuleCall_2_0_1ElementType() {
		return Property_TypeContentTypeIDTerminalRuleCall_2_0_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getProperty_Group_3ElementType() {
		return Property_Group_3_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getProperty_ByKeyword_3_0ElementType() {
		return Property_ByKeyword_3_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getProperty_SelectorAssignment_3_1ElementType() {
		return Property_SelectorAssignment_3_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getProperty_SelectorContentSelectorParserRuleCall_3_1_0ElementType() {
		return Property_SelectorContentSelectorParserRuleCall_3_1_0_ELEMENT_TYPE;
	}

}
