/*
 * generated by Xtext 2.12.0
 */
package de.tgremple.siteanalyser.configuration.idea.lang;

import org.eclipse.xtext.idea.lang.AbstractXtextLanguage;

public final class ConfigurationLanguageLanguage extends AbstractXtextLanguage {

	public static final ConfigurationLanguageLanguage INSTANCE = new ConfigurationLanguageLanguage();

	private ConfigurationLanguageLanguage() {
		super("de.tgremple.siteanalyser.configuration.ConfigurationLanguage");
	}

}
