/*
 * generated by Xtext 2.12.0
 */
package de.tgremple.siteanalyser.configuration.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractConfigurationLanguageScopeProvider extends DelegatingScopeProvider {
}
