/**
 * generated by Xtext 2.12.0
 */
package de.tgremple.siteanalyser.configuration.ui.contentassist;

import de.tgremple.siteanalyser.configuration.ui.contentassist.AbstractConfigurationLanguageProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class ConfigurationLanguageProposalProvider extends AbstractConfigurationLanguageProposalProvider {
}
