/*
 * generated by Xtext 2.12.0
 */
package de.tgremple.siteanalyser.configuration.idea.completion;

import org.eclipse.xtext.common.idea.completion.TerminalsCompletionContributor;
import org.eclipse.xtext.idea.lang.AbstractXtextLanguage;

public class AbstractConfigurationLanguageCompletionContributor extends TerminalsCompletionContributor {
	public AbstractConfigurationLanguageCompletionContributor(AbstractXtextLanguage lang) {
		super(lang);
	}
}
