/*
 * generated by Xtext 2.12.0
 */
package de.tgremple.siteanalyser.configuration.idea.completion

import de.tgremple.siteanalyser.configuration.idea.lang.ConfigurationLanguageLanguage
import org.eclipse.xtext.idea.lang.AbstractXtextLanguage

class ConfigurationLanguageCompletionContributor extends AbstractConfigurationLanguageCompletionContributor {
	new() {
		this(ConfigurationLanguageLanguage.INSTANCE)
	}
	
	new(AbstractXtextLanguage lang) {
		super(lang)
		//custom rules here
	}
}
