/**
 * generated by Xtext 2.12.0
 */
package de.tgremple.siteanalyser.configuration.ide;

import de.tgremple.siteanalyser.configuration.ide.AbstractConfigurationLanguageIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class ConfigurationLanguageIdeModule extends AbstractConfigurationLanguageIdeModule {
}
