/**
 * generated by Xtext 2.12.0
 */
package de.tgremple.siteanalyser.configuration.validation;

import de.tgremple.siteanalyser.configuration.validation.AbstractConfigurationLanguageValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ConfigurationLanguageValidator extends AbstractConfigurationLanguageValidator {
}
