/*
 * generated by Xtext 2.12.0
 */
package de.tgremple.siteanalyser.configuration.idea.lang.psi;

import com.intellij.psi.util.PsiModificationTracker;
import de.tgremple.siteanalyser.configuration.idea.lang.ConfigurationLanguageLanguage;
import org.eclipse.xtext.psi.BaseXtextCodeBlockModificationListener;

public class ConfigurationLanguageCodeBlockModificationListener extends BaseXtextCodeBlockModificationListener {

	public ConfigurationLanguageCodeBlockModificationListener(PsiModificationTracker psiModificationTracker) {
		super(ConfigurationLanguageLanguage.INSTANCE, psiModificationTracker);
	}

}
