/*
 * generated by Xtext 2.12.0
 */
package de.koalaworks.wccs.wcml


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class WebContentModelingLanguageStandaloneSetup extends WebContentModelingLanguageStandaloneSetupGenerated {

	def static void doSetup() {
		new WebContentModelingLanguageStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
