/*
 * generated by Xtext 2.12.0
 */
package de.koalaworks.wccs.wcml

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class WebpageContentModelingLanguageRuntimeModule extends AbstractWebpageContentModelingLanguageRuntimeModule {

	override bindIValueConverterService() {
		return WebpageContentModelingLanguageTerminalConverters
	}
}
