/*
 * generated by Xtext 2.12.0
 */
package de.koalaworks.wcts


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class TypeDefinitionLanguageStandaloneSetup extends TypeDefinitionLanguageStandaloneSetupGenerated {

	def static void doSetup() {
		new TypeDefinitionLanguageStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
