/*
 * generated by Xtext 2.12.0
 */
package de.koalaworks.wccs.wcml.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Test
import org.junit.runner.RunWith
import org.eclipse.xtext.testing.validation.ValidationTestHelper
import de.koalaworks.wccs.wcml.webContentModelingLanguage.ClassificationModel

@RunWith(XtextRunner)
@InjectWith(WebContentModelingLanguageInjectorProvider)
class WebContentModelingLanguageParsingTest {
	
	@Inject
	extension ParseHelper<ClassificationModel>
	
	@Inject
	extension ValidationTestHelper
	
	private val SELECTOR_START = "«"
	private val SELECTOR_END = "»"
	
	@Test
	def void loadModel() {
		val result = 
		'''
		content class cType1 is recognized by css «SELECTOR_START»h1«SELECTOR_END»
		reference class rType1 is recognized by css «SELECTOR_START»a.test«SELECTOR_END»
		page class pType1 is recognized by url pattern «SELECTOR_START»123«SELECTOR_END»
		    classifies f1 as cType1
		               f2 as rType1
		'''.parse

		result.assertNoErrors
	}
}
