/*
 * generated by Xtext 2.12.0
 */
package de.koalaworks.wccs.wcml.ide


/**
 * Use this class to register ide components.
 */
class TypeDefinitionLanguageIdeModule extends AbstractTypeDefinitionLanguageIdeModule {
}
