/*
 * generated by Xtext 2.12.0
 */
package de.koalaworks.wccs.wcml.ide

import com.google.inject.Guice
import de.koalaworks.wccs.wcml.WebpageContentModelingLanguageRuntimeModule
import de.koalaworks.wccs.wcml.WebpageContentModelingLanguageStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class WebpageContentModelingLanguageIdeSetup extends WebpageContentModelingLanguageStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new WebpageContentModelingLanguageRuntimeModule, new WebpageContentModelingLanguageIdeModule))
	}
	
}
