/*
 * generated by Xtext 2.12.0
 */
package de.tgremple.siteanalyser.configuration.serializer;

import com.google.inject.Inject;
import de.tgremple.siteanalyser.configuration.services.ConfigurationLanguageGrammarAccess;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class ConfigurationLanguageSyntacticSequencer extends AbstractSyntacticSequencer {

	protected ConfigurationLanguageGrammarAccess grammarAccess;
	protected AbstractElementAlias match_ContentType_RecognizeKeyword_4_0_q;
	protected AbstractElementAlias match_PageType_RecognizeKeyword_7_0_q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (ConfigurationLanguageGrammarAccess) access;
		match_ContentType_RecognizeKeyword_4_0_q = new TokenAlias(false, true, grammarAccess.getContentTypeAccess().getRecognizeKeyword_4_0());
		match_PageType_RecognizeKeyword_7_0_q = new TokenAlias(false, true, grammarAccess.getPageTypeAccess().getRecognizeKeyword_7_0());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_ContentType_RecognizeKeyword_4_0_q.equals(syntax))
				emit_ContentType_RecognizeKeyword_4_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_PageType_RecognizeKeyword_7_0_q.equals(syntax))
				emit_PageType_RecognizeKeyword_7_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     'recognize'?
	 *
	 * This ambiguous syntax occurs at:
	 *     name=ID (ambiguity) (rule end)
	 *     selector=ContentSelector (ambiguity) (rule end)
	 */
	protected void emit_ContentType_RecognizeKeyword_4_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     'recognize'?
	 *
	 * This ambiguous syntax occurs at:
	 *     selector=PageSelector (ambiguity) (rule end)
	 */
	protected void emit_PageType_RecognizeKeyword_7_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
