/*
 * generated by Xtext 2.12.0
 */
package de.tgremple.siteanalyser.configuration


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ConfigurationLanguageStandaloneSetup extends ConfigurationLanguageStandaloneSetupGenerated {

	def static void doSetup() {
		new ConfigurationLanguageStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
