/*
 * generated by Xtext 2.12.0
 */
package de.tgremple.siteanalyser.configuration


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class ConfigurationLanguageRuntimeModule extends AbstractConfigurationLanguageRuntimeModule {
}
