/*
 * generated by Xtext 2.12.0
 */
package de.tgremple.siteanalyser.configuration.idea.highlighting;

import de.tgremple.siteanalyser.configuration.idea.lang.ConfigurationLanguageLanguage;
import org.eclipse.xtext.idea.highlighting.SemanticHighlightVisitor;

public class ConfigurationLanguageSemanticHighlightVisitor extends SemanticHighlightVisitor {
	public ConfigurationLanguageSemanticHighlightVisitor() {
		ConfigurationLanguageLanguage.INSTANCE.injectMembers(this);
	}
}
