/*
 * generated by Xtext 2.12.0
 */
package de.tgremple.siteanalyser.configuration.idea.highlighting;

import com.intellij.openapi.fileTypes.SingleLazyInstanceSyntaxHighlighterFactory;
import com.intellij.openapi.fileTypes.SyntaxHighlighter;
import de.tgremple.siteanalyser.configuration.idea.lang.ConfigurationLanguageLanguage;
import org.jetbrains.annotations.NotNull;

public class ConfigurationLanguageSyntaxHighlighterFactory extends SingleLazyInstanceSyntaxHighlighterFactory {
	
	@Override
	@NotNull
	protected SyntaxHighlighter createHighlighter() {
		return ConfigurationLanguageLanguage.INSTANCE.getInstance(SyntaxHighlighter.class);
	}
}
