/*
 * generated by Xtext 2.12.0
 */
package de.tgremple.siteanalyser.configuration.idea.highlighting;

import de.tgremple.siteanalyser.configuration.idea.lang.ConfigurationLanguageLanguage;
import org.eclipse.xtext.idea.highlighting.AbstractColorSettingsPage;

public class ConfigurationLanguageBaseColorSettingsPage extends AbstractColorSettingsPage {
	
	public ConfigurationLanguageBaseColorSettingsPage() {
		ConfigurationLanguageLanguage.INSTANCE.injectMembers(this);
	}

	@Override
	public String getDisplayName() {
		return ConfigurationLanguageLanguage.INSTANCE.getDisplayName();
	}
}
