/**
 * generated by Xtext 2.12.0
 */
package de.tgremple.siteanalyser.configuration.ui;

import de.tgremple.siteanalyser.configuration.ui.AbstractConfigurationLanguageUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class ConfigurationLanguageUiModule extends AbstractConfigurationLanguageUiModule {
  public ConfigurationLanguageUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
