/**
 * generated by Xtext 2.12.0
 */
package de.tgremple.siteanalyser.configuration.idea.lang;

import de.tgremple.siteanalyser.configuration.idea.lang.AbstractConfigurationLanguageFileType;

@SuppressWarnings("all")
public class ConfigurationLanguageFileType extends AbstractConfigurationLanguageFileType {
  public final static ConfigurationLanguageFileType INSTANCE = new ConfigurationLanguageFileType();
  
  public ConfigurationLanguageFileType() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method super(ConfigurationLanguageLanguage) is undefined");
  }
}
