/*
 * generated by Xtext 2.12.0
 */
package de.tgremple.siteanalyser.configuration.tests

import com.google.inject.Inject
import de.tgremple.siteanalyser.configuration.configurationLanguage.SiteStructure
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(ConfigurationLanguageInjectorProvider)
class ConfigurationLanguageParsingTest {
	@Inject
	ParseHelper<SiteStructure> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
		Assert.assertTrue(result.eResource.errors.isEmpty)
	}
}
