/*
 * generated by Xtext 2.12.0
 */
package de.tgremple.siteanalyser.configuration.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractConfigurationLanguageValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(de.tgremple.siteanalyser.configuration.configurationLanguage.ConfigurationLanguagePackage.eINSTANCE);
		return result;
	}
	
}
