/**
 * generated by Xtext 2.12.0
 */
package de.tgremple.siteanalyser.configuration.idea;

@SuppressWarnings("all")
public class ConfigurationLanguageIdeaSetup /* implements ISetup  */{
  @Override
  public Object createInjectorAndDoEMFRegistration() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field EcoreGlobalRegistries is undefined"
      + "\nThe method createInjector() from the type ConfigurationLanguageStandaloneSetupIdea refers to the missing type Object"
      + "\nensureInitialized cannot be resolved");
  }
}
