/**
 * generated by Xtext 2.12.0
 */
package de.tgremple.siteanalyser.configuration.idea;

import de.tgremple.siteanalyser.configuration.idea.AbstractConfigurationLanguageIdeaModule;

/**
 * Use this class to register components to be used within IntelliJ IDEA.
 */
@SuppressWarnings("all")
public class ConfigurationLanguageIdeaModule extends AbstractConfigurationLanguageIdeaModule {
}
