/**
 * generated by Xtext 2.12.0
 */
package de.tgremple.siteanalyser.configuration.idea;

@SuppressWarnings("all")
public class ConfigurationLanguageStandaloneSetupIdea /* implements ConfigurationLanguageStandaloneSetupGenerated  */{
  @Override
  public Object createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nConfigurationLanguageRuntimeModule cannot be resolved."
      + "\nThe method or field Modules2 is undefined"
      + "\nThe method or field Guice is undefined"
      + "\nmixin cannot be resolved"
      + "\ncreateInjector cannot be resolved");
  }
}
