/*
 * generated by Xtext 2.12.0
 */
package de.tgremple.siteanalyser.configuration.ide


/**
 * Use this class to register ide components.
 */
class ConfigurationLanguageIdeModule extends AbstractConfigurationLanguageIdeModule {
}
