/**
 * generated by Xtext 2.12.0
 */
package de.tgremple.siteanalyser.configuration.configurationLanguage.impl;

import de.tgremple.siteanalyser.configuration.configurationLanguage.*;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class ConfigurationLanguageFactoryImpl extends EFactoryImpl implements ConfigurationLanguageFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static ConfigurationLanguageFactory init()
  {
    try
    {
      ConfigurationLanguageFactory theConfigurationLanguageFactory = (ConfigurationLanguageFactory)EPackage.Registry.INSTANCE.getEFactory(ConfigurationLanguagePackage.eNS_URI);
      if (theConfigurationLanguageFactory != null)
      {
        return theConfigurationLanguageFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new ConfigurationLanguageFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ConfigurationLanguageFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case ConfigurationLanguagePackage.SITE_STRUCTURE: return createSiteStructure();
      case ConfigurationLanguagePackage.TYPE: return createType();
      case ConfigurationLanguagePackage.CONTENT_TYPE: return createContentType();
      case ConfigurationLanguagePackage.PAGE_TYPE: return createPageType();
      case ConfigurationLanguagePackage.CONTENT_SELECTOR: return createContentSelector();
      case ConfigurationLanguagePackage.PAGE_SELECTOR: return createPageSelector();
      case ConfigurationLanguagePackage.CSS_SELECTOR: return createCssSelector();
      case ConfigurationLanguagePackage.URL_PATTERN_SELECTOR: return createUrlPatternSelector();
      case ConfigurationLanguagePackage.PROPERTY: return createProperty();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SiteStructure createSiteStructure()
  {
    SiteStructureImpl siteStructure = new SiteStructureImpl();
    return siteStructure;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Type createType()
  {
    TypeImpl type = new TypeImpl();
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ContentType createContentType()
  {
    ContentTypeImpl contentType = new ContentTypeImpl();
    return contentType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PageType createPageType()
  {
    PageTypeImpl pageType = new PageTypeImpl();
    return pageType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ContentSelector createContentSelector()
  {
    ContentSelectorImpl contentSelector = new ContentSelectorImpl();
    return contentSelector;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PageSelector createPageSelector()
  {
    PageSelectorImpl pageSelector = new PageSelectorImpl();
    return pageSelector;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CssSelector createCssSelector()
  {
    CssSelectorImpl cssSelector = new CssSelectorImpl();
    return cssSelector;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public UrlPatternSelector createUrlPatternSelector()
  {
    UrlPatternSelectorImpl urlPatternSelector = new UrlPatternSelectorImpl();
    return urlPatternSelector;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Property createProperty()
  {
    PropertyImpl property = new PropertyImpl();
    return property;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ConfigurationLanguagePackage getConfigurationLanguagePackage()
  {
    return (ConfigurationLanguagePackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static ConfigurationLanguagePackage getPackage()
  {
    return ConfigurationLanguagePackage.eINSTANCE;
  }

} //ConfigurationLanguageFactoryImpl
