/**
 * generated by Xtext 2.12.0
 */
package de.tgremple.siteanalyser.configuration.idea.highlighting;

import de.tgremple.siteanalyser.configuration.idea.highlighting.ConfigurationLanguageBaseColorSettingsPage;

@SuppressWarnings("all")
public class ConfigurationLanguageColorSettingsPage extends ConfigurationLanguageBaseColorSettingsPage {
}
