/**
 * generated by Xtext 2.12.0
 */
package de.tgremple.siteanalyser.configuration.idea.completion;

import de.tgremple.siteanalyser.configuration.idea.completion.AbstractConfigurationLanguageCompletionContributor;

@SuppressWarnings("all")
public class ConfigurationLanguageCompletionContributor extends AbstractConfigurationLanguageCompletionContributor {
  public ConfigurationLanguageCompletionContributor() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe constructor ConfigurationLanguageCompletionContributor(AbstractXtextLanguage) refers to the missing type AbstractXtextLanguage");
  }
  
  public ConfigurationLanguageCompletionContributor(final /* AbstractXtextLanguage */Object lang) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method super(AbstractXtextLanguage) is undefined");
  }
}
