/*
 * generated by Xtext 2.12.0
 */
package de.tgremple.siteanalyser.configuration.idea;

import com.intellij.openapi.extensions.ExtensionFactory;
import de.tgremple.siteanalyser.configuration.idea.lang.ConfigurationLanguageLanguage;

public class ConfigurationLanguageExtensionFactory implements ExtensionFactory {
	@Override
	public Object createInstance(String factoryArgument, String implementationClass) {
		Class<?> clazz;
		try {
			clazz = Class.forName(implementationClass);
		} catch (ClassNotFoundException e) {
			throw new IllegalArgumentException("Couldn't load "+implementationClass, e);
		}
		return ConfigurationLanguageLanguage.INSTANCE.<Object> getInstance(clazz);
	}
}
