/*
 * generated by Xtext 2.12.0
 */
package de.tgremple.siteanalyser.configuration.idea.lang


class ConfigurationLanguageFileType extends AbstractConfigurationLanguageFileType {
	public static final ConfigurationLanguageFileType INSTANCE = new ConfigurationLanguageFileType()
	
	new() {
		super(ConfigurationLanguageLanguage.INSTANCE)
	}
}
