/*
 * generated by Xtext 2.12.0
 */
package de.tgremple.siteanalyser.configuration.idea.lang.pom;

import de.tgremple.siteanalyser.configuration.idea.lang.ConfigurationLanguageLanguage;
import org.eclipse.xtext.idea.pom.AbstractXtextPomDeclarationSearcher;

public class ConfigurationLanguagePomDeclarationSearcher extends AbstractXtextPomDeclarationSearcher {

	public ConfigurationLanguagePomDeclarationSearcher() {
		super(ConfigurationLanguageLanguage.INSTANCE);
	}
}
