/**
 * generated by Xtext 2.12.0
 */
package de.tgremple.siteanalyser.configuration;

import de.tgremple.siteanalyser.configuration.ConfigurationLanguageStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class ConfigurationLanguageStandaloneSetup extends ConfigurationLanguageStandaloneSetupGenerated {
  public static void doSetup() {
    new ConfigurationLanguageStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
