/**
 * generated by Xtext 2.12.0
 */
package de.tgremple.siteanalyser.configuration;

import de.tgremple.siteanalyser.configuration.AbstractConfigurationLanguageRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class ConfigurationLanguageRuntimeModule extends AbstractConfigurationLanguageRuntimeModule {
}
