/*
 * generated by Xtext 2.12.0
 */
package de.tgremple.siteanalyser.configuration.ui;

import com.google.inject.Injector;
import de.tgremple.siteanalyser.configuration.language.ui.internal.LanguageActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ConfigurationLanguageExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return LanguageActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return LanguageActivator.getInstance().getInjector(LanguageActivator.DE_TGREMPLE_SITEANALYSER_CONFIGURATION_CONFIGURATIONLANGUAGE);
	}
	
}
